@echo off
rem Eco Observatory launcher (v0.3.1, 2026-09-15)
rem Double-click: start silent service (pythonw) + native window (pywebview).
rem Already running on 8788: just opens another window. Close: close the window.
rem Keep this file ASCII + relative (%~dp0) for open-source portability.
rem Desktop copies are pointers generated by install_desktop.py.
set "PYW="
where pythonw >nul 2>nul && set "PYW=pythonw"
if not defined PYW where pyw >nul 2>nul && set "PYW=pyw"
if defined PYW goto run
echo [ERROR] pythonw not found. Install Python 3.10+ (python.org or conda), or run:
echo   py -3 "%~dp0eco_gui.py"
pause
exit /b 1
:run
start "" %PYW% "%~dp0eco_gui.py"
