@echo off
chcp 65001 >nul
title 生态急救箱
rem First-aid entry: diagnose + fix + restart GUI service + open window.
rem Lives next to first_aid.py; relative path only (open-source friendly).
rem Desktop copies are pointers generated by install_desktop.py --
rem never hand-copy absolute paths into this file.
echo 正在启动生态急救箱（自检 + 修复 + 重启服务 + 开窗）…
set "PY=python"
where python >nul 2>nul || set "PY=py -3"
%PY% "%~dp0first_aid.py" --fix
set "RC=%errorlevel%"
if "%RC%"=="2" goto fail
if "%RC%"=="9009" goto fail
echo.
echo 急救箱流程结束，本窗口可关闭。
pause
exit /b 0
:fail
echo.
echo [错误] 急救箱未能运行（退出码 %RC%）。
echo 请检查：Python 已安装并在 PATH；first_aid.py 与本脚本同目录。
pause
exit /b 1
